#!/bin/bash

echo "Starting launch script..."

dir="/bro"
export QT_QPA_PLATFORM=eglfs
export QT_QPA_EGLFS_KMS_CONFIG=eglfs_kms_conf.json

cd "${dir}" && \
echo "Starting launch.py..."
python launcher/launch.py
echo "Exiting launch script..."