#!/bin/bash

echo "Starting launch script..."

dir="/bro"
export QT_QPA_PLATFORM=eglfs
export QT_QPA_EGLFS_KMS_CONFIG=launcher/eglfs_kms_conf.json

cd "${dir}" && \
while true; do
    python git/py/launch.py
    if [ $? -eq 0 ]; do
        sleep 5
        echo "Restarting script..."
    else
        echo "There was a problem running the launch script, not restarting."
        exit 1
    fi
done
