#!/bin/bash

echo "Starting launch script..."

dir="/bro"
export QT_QPA_PLATFORM=eglfs
export QT_QPA_EGLFS_KMS_CONFIG=launcher/eglfs_kms_conf.json

cd "${dir}" && \
while true; do
    python git/py/launch.py
    if [ $? -eq 130 ]; then
        echo "Launch script has been manually shut down, not restarting."
        exit 1
    else
        echo "Restarting script..."
        sleep 5
    fi
done
