#!/bin/bash

dir="/bro"

cd "${dir}"
{ # try
    echo "Checking for software updates..."

    ping "github.com" -c 5 -w 10 >/dev/null && \
    git_branch="$(cat branch)" && \
    cd "${dir}/git" && \
    git stash && \
    git switch "${git_branch}" && \
    git fetch && \
    git pull && \
    echo "Done!"
} || {
    echo "Error when checking for updates, please check internet connection."
}

echo "Exiting update script..."
