#!/bin/bash

dir="/bro"

cd "${dir}"
{ # try
    echo "Checking for software updates..."
    
    ping "github.com" >/dev/null && \
    git_branch="$(cat branch)" && \
    cd "${dir}/git" && \
    git stash && \
    git switch "${git_branch}" && \
    git fetch && \
    git pull
} || {
    echo "Error when checking for updates, please check internet connection."
}
